# Generated by Django 5.0.6 on 2024-06-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_fr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
